//! Integration test: ACME over a real TLS socket.
//!
//! Spins up the actual `axum-server` TLS stack against an in-memory SQLite
//! database and a freshly generated CA. A minimal rustls client (trusting the
//! Akāmu CA) connects over a loopback socket and drives the ACME protocol:
//!
//!   GET  /acme/directory → 200, correct content-type
//!   HEAD /acme/new-nonce → 200, Replay-Nonce header present
//!   POST /acme/new-account (JWS with JWK) → 201, Location header present
//!
//! The server certificate is auto-generated by `tls::init::load_or_generate`
//! (the CA-signed bootstrap path) so no external cert files are needed.

use std::sync::Arc;

use axum::http::header;
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use hyper::body::Bytes;
use hyper_util::rt::TokioIo;
use rustls::pki_types::{CertificateDer, ServerName};
use serde_json::{json, Value};
use synta_certificate::{BackendPrivateKey, CertificateSigner as _, PrivateKey as _};
use tokio::net::TcpStream;
use tokio_rustls::TlsConnector;

use acme_server::config::{
    CaConfig, Config, DatabaseConfig, MtcConfig, ServerConfig, TlsConfig,
};
use acme_server::state::{AppState, CaState, MtcState};
use acme_server::{ca, db, routes, tls};

// ── Minimal ACME JWS signer (P-256 / ES256) ──────────────────────────────────

struct AcmeKey {
    key: BackendPrivateKey,
    x_b64: String,
    y_b64: String,
}

impl AcmeKey {
    fn generate() -> Self {
        let key = BackendPrivateKey::generate_ec("P-256").unwrap();
        let pub_key = key.public_key().unwrap();
        let (x_bytes, y_bytes) = pub_key.ec_affine_coordinates().unwrap().unwrap();
        let x_b64 = encode_coord(&x_bytes, 32);
        let y_b64 = encode_coord(&y_bytes, 32);
        AcmeKey { key, x_b64, y_b64 }
    }

    fn jwk(&self) -> Value {
        json!({ "kty": "EC", "crv": "P-256", "x": self.x_b64, "y": self.y_b64 })
    }

    fn jws_with_jwk(&self, nonce: &str, url: &str, payload: Option<Value>) -> Value {
        let header = json!({
            "alg": "ES256",
            "nonce": nonce,
            "url": url,
            "jwk": self.jwk(),
        });
        self.build_jws(header, payload)
    }

    fn build_jws(&self, header: Value, payload: Option<Value>) -> Value {
        let protected = URL_SAFE_NO_PAD.encode(header.to_string().as_bytes());
        let payload_b64 = match payload {
            Some(v) => URL_SAFE_NO_PAD.encode(v.to_string().as_bytes()),
            None => String::new(),
        };
        let signing_input = format!("{}.{}", protected, payload_b64);
        let signer = self.key.as_signer("sha256");
        let der_sig = signer.sign_tbs(signing_input.as_bytes()).unwrap();
        let p1363 = ecdsa_der_to_p1363(&der_sig, 32).unwrap();
        let signature = URL_SAFE_NO_PAD.encode(&p1363);
        json!({ "protected": protected, "payload": payload_b64, "signature": signature })
    }
}

fn encode_coord(bytes: &[u8], len: usize) -> String {
    let mut padded = vec![0u8; len];
    let start = len.saturating_sub(bytes.len());
    padded[start..].copy_from_slice(&bytes[bytes.len().saturating_sub(len)..]);
    URL_SAFE_NO_PAD.encode(&padded)
}

fn ecdsa_der_to_p1363(der: &[u8], half: usize) -> Option<Vec<u8>> {
    let inner = strip_tlv(der, 0x30)?;
    let (r, rest) = strip_integer(inner)?;
    let (s, _) = strip_integer(rest)?;
    if r.len() > half || s.len() > half {
        return None;
    }
    let mut out = vec![0u8; half * 2];
    out[half - r.len()..half].copy_from_slice(r);
    out[half * 2 - s.len()..].copy_from_slice(s);
    Some(out)
}

fn strip_tlv<'a>(buf: &'a [u8], tag: u8) -> Option<&'a [u8]> {
    if *buf.first()? != tag { return None; }
    let (len, rest) = decode_der_len(&buf[1..])?;
    rest.get(..len)
}

fn strip_integer(buf: &[u8]) -> Option<(&[u8], &[u8])> {
    if *buf.first()? != 0x02 { return None; }
    let (len, rest) = decode_der_len(&buf[1..])?;
    let val = rest.get(..len)?;
    let val = val.strip_prefix(&[0x00u8]).unwrap_or(val);
    Some((val, &rest[len..]))
}

fn decode_der_len(buf: &[u8]) -> Option<(usize, &[u8])> {
    let first = *buf.first()?;
    if first < 0x80 {
        Some((first as usize, &buf[1..]))
    } else if first == 0x81 {
        Some((*buf.get(1)? as usize, &buf[2..]))
    } else if first == 0x82 {
        let len = (*buf.get(1)? as usize) << 8 | *buf.get(2)? as usize;
        Some((len, &buf[3..]))
    } else {
        None
    }
}

// ── HTTPS test client ─────────────────────────────────────────────────────────

/// Build a rustls `ClientConfig` that trusts only the given CA DER.
///
/// Explicitly installs the ring provider (tests have no `main()` to call
/// `CryptoProvider::install_default()`).
fn client_tls_config(ca_der: &[u8]) -> rustls::ClientConfig {
    let mut root_store = rustls::RootCertStore::empty();
    root_store
        .add(CertificateDer::from(ca_der.to_vec()))
        .expect("add CA cert to root store");
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    rustls::ClientConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .expect("safe protocol versions")
        .with_root_certificates(root_store)
        .with_no_client_auth()
}

/// Result of one HTTPS request.
struct Response {
    status: u16,
    headers: hyper::http::HeaderMap,
    body: String,
}

/// Open a fresh TLS connection to `addr` (SNI = "localhost") and send one
/// HTTP/1.1 request. Returns after the response body is fully received.
async fn https(
    addr: std::net::SocketAddr,
    method: &str,
    path: &str,
    req_headers: &[(&str, &str)],
    body: Option<String>,
    ca_der: &[u8],
) -> Response {
    let connector = TlsConnector::from(Arc::new(client_tls_config(ca_der)));
    let stream = TcpStream::connect(addr).await.expect("TCP connect");
    let server_name = ServerName::try_from("localhost").unwrap();
    let tls_stream = connector
        .connect(server_name, stream)
        .await
        .expect("TLS handshake");

    let io = TokioIo::new(tls_stream);
    let (mut sender, conn) = hyper::client::conn::http1::handshake(io)
        .await
        .expect("HTTP/1.1 handshake");
    tokio::spawn(conn);

    let body_bytes: Bytes = match body {
        Some(s) => Bytes::from(s),
        None => Bytes::new(),
    };
    let content_len = body_bytes.len();

    let mut builder = hyper::Request::builder()
        .method(method)
        .uri(format!("https://localhost:{}{}", addr.port(), path))
        .header(header::HOST, "localhost");
    for (name, val) in req_headers {
        builder = builder.header(*name, *val);
    }
    if content_len > 0 {
        builder = builder.header(header::CONTENT_LENGTH, content_len);
    }
    let req = builder
        .body(http_body_util::Full::new(body_bytes))
        .unwrap();

    let resp = sender.send_request(req).await.expect("send request");
    let status = resp.status().as_u16();
    let headers = resp.headers().clone();
    let body_bytes = http_body_util::BodyExt::collect(resp.into_body())
        .await
        .expect("read body")
        .to_bytes();
    let body = String::from_utf8_lossy(&body_bytes).into_owned();

    Response { status, headers, body }
}

// ── Server setup ──────────────────────────────────────────────────────────────

struct TlsTestServer {
    addr: std::net::SocketAddr,
    /// CA certificate DER — used to build the client trust store.
    ca_der: Vec<u8>,
    /// tokio task handle — abort on drop to free the port.
    handle: tokio::task::JoinHandle<()>,
    /// Temp dir kept alive as long as the server lives.
    _dir: tempfile::TempDir,
}

impl Drop for TlsTestServer {
    fn drop(&mut self) {
        self.handle.abort();
    }
}

/// Spin up a full TLS ACME server on a random loopback port.
///
/// Uses `axum_server::from_tcp_rustls` with a bootstrap CA-signed server cert.
/// The server task runs until the returned `TlsTestServer` is dropped.
async fn start_tls_server() -> TlsTestServer {
    let dir = tempfile::TempDir::new().unwrap();

    // Bind the listener first so we know the actual port before building config.
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    listener.set_nonblocking(true).unwrap();
    let addr = listener.local_addr().unwrap();
    let base_url = format!("https://localhost:{}", addr.port());

    // Config — TLS enabled, bootstrap key ec:P-256.
    let cert_file = dir.path().join("server.crt").to_string_lossy().into_owned();
    let key_file = dir.path().join("server.key").to_string_lossy().into_owned();

    let config = Arc::new(Config {
        listen_addr: format!("127.0.0.1:{}", addr.port()),
        base_url: base_url.clone(),
        database: DatabaseConfig { path: ":memory:".into() },
        ca: CaConfig {
            key_file: dir.path().join("ca.key").to_string_lossy().into_owned(),
            cert_file: dir.path().join("ca.crt").to_string_lossy().into_owned(),
            key_type: "ec:P-256".into(),
            hash_alg: "sha256".into(),
            validity_days: 90,
            crl_url: None,
            ocsp_url: None,
            common_name: "TLS Test CA".into(),
            organization: "Test Org".into(),
            ca_validity_years: 10,
        },
        mtc: MtcConfig { log_path: "/dev/null".into(), enabled: false },
        server: ServerConfig::default(),
        tls: TlsConfig {
            enabled: true,
            cert_file: cert_file.clone(),
            key_file: key_file.clone(),
            protocols: vec!["TLSv1.2".into(), "TLSv1.3".into()],
            server_name: "localhost".into(),
            bootstrap_key_type: "ec:P-256".into(),
            client_auth: None,
        },
    });

    // Initialise CA.
    let (ca_key, ca_cert_der) = ca::init::load_or_generate(&config.ca).unwrap();
    let ca_der_clone = ca_cert_der.clone();
    let db_conn = Arc::new(db::open(":memory:").await.unwrap());

    let ca_state = Arc::new(CaState {
        key: ca_key,
        cert_der: ca_cert_der,
        hash_alg: "sha256".into(),
        validity_days: 90,
        crl_url: None,
        ocsp_url: None,
    });

    // Bootstrap TLS cert/key (generates a CA-signed server cert in the tempdir).
    tls::init::load_or_generate(&config.tls, &ca_state).unwrap();

    // Build rustls ServerConfig.
    let server_cfg = tls::build_rustls_server_config(&config.tls).unwrap();
    let rustls_cfg = axum_server::tls_rustls::RustlsConfig::from_config(Arc::new(server_cfg));

    let state = Arc::new(AppState {
        config: Arc::clone(&config),
        db: Arc::clone(&db_conn),
        ca: ca_state,
        mtc: Arc::new(MtcState {
            log: None,
            algorithm: synta_mtc::crypto::HashAlgorithm::Sha256,
        }),
        tls: None,
    });

    let router = routes::build_router(Arc::clone(&state));

    let handle = tokio::spawn(async move {
        axum_server::from_tcp_rustls(listener, rustls_cfg)
            .expect("bind TLS listener")
            .serve(
                router.into_make_service_with_connect_info::<std::net::SocketAddr>(),
            )
            .await
            .unwrap();
    });

    // Give the server a moment to accept the first connection.
    tokio::time::sleep(std::time::Duration::from_millis(50)).await;

    TlsTestServer { addr, ca_der: ca_der_clone, handle, _dir: dir }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

/// GET /acme/directory over TLS returns 200 with the expected JSON structure.
#[tokio::test]
async fn test_tls_directory() {
    let server = start_tls_server().await;

    let r = https(server.addr, "GET", "/acme/directory", &[], None, &server.ca_der).await;

    assert_eq!(r.status, 200, "directory: expected 200, got {}: {}", r.status, r.body);
    assert!(
        r.headers
            .get(header::CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .map(|ct| ct.contains("application/json"))
            .unwrap_or(false),
        "directory: Content-Type should be application/json"
    );

    let dir: Value = serde_json::from_str(&r.body).expect("directory response is JSON");
    assert!(dir["newAccount"].is_string(), "directory missing newAccount");
    assert!(dir["newNonce"].is_string(), "directory missing newNonce");
    assert!(dir["newOrder"].is_string(), "directory missing newOrder");
}

/// HEAD /acme/new-nonce returns 200 with a Replay-Nonce header.
#[tokio::test]
async fn test_tls_new_nonce() {
    let server = start_tls_server().await;

    let r = https(server.addr, "HEAD", "/acme/new-nonce", &[], None, &server.ca_der).await;

    assert_eq!(r.status, 200, "new-nonce: expected 200, got {}", r.status);
    assert!(
        r.headers.contains_key("replay-nonce"),
        "new-nonce: missing Replay-Nonce header"
    );
}

/// Full ACME new-account registration over TLS: nonce → new-account → 201.
#[tokio::test]
async fn test_tls_new_account() {
    let server = start_tls_server().await;
    let port = server.addr.port();
    let base_url = format!("https://localhost:{port}");

    // Step 1: fetch a nonce.
    let nonce_r = https(server.addr, "HEAD", "/acme/new-nonce", &[], None, &server.ca_der).await;
    assert_eq!(nonce_r.status, 200);
    let nonce = nonce_r
        .headers
        .get("replay-nonce")
        .unwrap()
        .to_str()
        .unwrap()
        .to_string();

    // Step 2: POST new-account.
    let key = AcmeKey::generate();
    let new_account_url = format!("{base_url}/acme/new-account");
    let jws = key.jws_with_jwk(
        &nonce,
        &new_account_url,
        Some(json!({ "termsOfServiceAgreed": true })),
    );

    let r = https(
        server.addr,
        "POST",
        "/acme/new-account",
        &[("Content-Type", "application/jose+json")],
        Some(jws.to_string()),
        &server.ca_der,
    )
    .await;

    assert_eq!(
        r.status, 201,
        "new-account: expected 201 Created, got {}: {}",
        r.status, r.body
    );
    assert!(
        r.headers.contains_key("location"),
        "new-account: missing Location header (account URL)"
    );

    let body: Value = serde_json::from_str(&r.body).expect("new-account response is JSON");
    assert_eq!(body["status"], "valid", "account status should be 'valid'");

    let location = r.headers["location"].to_str().unwrap();
    eprintln!("TLS new-account: account URL = {location}");
}

/// Verify that a client trusting a *different* CA is rejected (TLS handshake fails).
///
/// This exercises that the server certificate is actually being validated — i.e.,
/// the server is not using a globally trusted cert that any CA would accept.
#[tokio::test]
async fn test_tls_untrusted_ca_rejected() {
    let server = start_tls_server().await;

    // Generate a fresh unrelated CA — not trusted by this server.
    let dir = tempfile::TempDir::new().unwrap();
    let unrelated_ca_cfg = CaConfig {
        key_file: dir.path().join("other-ca.key").to_string_lossy().into_owned(),
        cert_file: dir.path().join("other-ca.crt").to_string_lossy().into_owned(),
        key_type: "ec:P-256".into(),
        hash_alg: "sha256".into(),
        validity_days: 90,
        crl_url: None,
        ocsp_url: None,
        common_name: "Unrelated CA".into(),
        organization: "Other".into(),
        ca_validity_years: 10,
    };
    let (_, other_ca_der) = ca::init::load_or_generate(&unrelated_ca_cfg).unwrap();

    // Attempt TLS handshake trusting only the unrelated CA — must fail.
    let connector = TlsConnector::from(Arc::new(client_tls_config(&other_ca_der)));
    let stream = TcpStream::connect(server.addr).await.unwrap();
    let server_name = ServerName::try_from("localhost").unwrap();
    let result = connector.connect(server_name, stream).await;

    assert!(
        result.is_err(),
        "TLS handshake should fail when client trusts an unrelated CA"
    );
}
