# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate akamu

Name:           rust-akamu
Version:        0.1.0
Release:        1%{?dist}
Summary:        ACME server with post-quantum certificate support

License:        GPL-3.0-or-later
URL:            https://PLACEHOLDER.example.com/akamu/archive/v{version}.tar.gz
Source:         %{crates_source}
Source:         akamu-0.1.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  openssl-devel
BuildRequires:  sqlite-devel
BuildRequires:  clang-devel

%global _description %{expand:
akamu is an ACME (RFC 8555) certificate authority server that supports
post-quantum cryptography via an ML-DSA/PQC-capable OpenSSL fork.  It
implements the full ACME protocol including http-01, dns-01, and tls-alpn-01
challenge types, and supports Merkle Tree Certificates (MTC) for
compressed certificate delivery.
}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%{_bindir}/akamu

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
# * Vendoring is required because [patch.crates-io] in Cargo.toml overrides
# * openssl and openssl-sys with a git fork (pqc-prs branch from
# * https://github.com/abbra/rust-openssl.git) for ML-DSA/ML-KEM/PQC
# * support.  This fork is not published to crates.io.
# * A vendor tarball (Source1) must be generated with 'cargo vendor' and
# * added alongside the forge source tarball before submission.
# * Rebuild this package whenever openssl-devel is updated in Fedora.
# * The project uses an OpenSSL fork (pqc-prs) for ML-DSA/PQ support;
# * verify compatibility when the system OpenSSL major version changes.
# * PREREQUISITE: the synta* path-dependencies are not part of this package
# * and must be installed into the mock chroot before this SRPM can build:
# *   rust-synta-devel, rust-synta-certificate-devel,
# *   rust-synta-x509-verification-devel, rust-synta-mtc-devel
# * Run 'mock --install' for each of those packages in dependency order
# * before running 'mock --rebuild' on this SRPM.
# * NOTE: tokio-rusqlite and rusqlite_migration are not yet packaged in
# * Fedora (as of 2026-04-11) and are included in the vendor tarball.
# * File separate Fedora review requests for those crates.
# * NOTE: axum-server 0.8 is required but only 0.7.3 is available in
# * Fedora (as of 2026-04-11).  axum-server 0.8 is also in the vendor
# * tarball.  A Fedora package update or new review may be needed.
%cargo_test
%endif

%changelog
