use serde::Deserialize;

mod admin;
mod ca;
mod db;
mod delegation;
mod gssapi;
mod ldap;
mod mtc;
mod profiles;
mod server;
mod tls;
mod webui;

pub use self::admin::*;
pub use self::ca::*;
pub use self::db::*;
pub use self::delegation::*;
pub use self::gssapi::*;
pub use self::ldap::*;
pub use self::mtc::*;
pub use self::profiles::*;
pub use self::server::*;
pub use self::tls::*;
pub use self::webui::*;

#[derive(Debug, Deserialize)]
pub struct Config {
    /// Address to listen on.  Accepts `host:port` for TCP (e.g. `"0.0.0.0:8080"`)
    /// or `unix:/path/to/socket` / `/path/to/socket` for a Unix domain socket.
    /// The `AKAMU_LISTEN` environment variable overrides this field.
    /// Unix domain sockets cannot be combined with `[tls]`.
    pub listen_addr: String,
    /// Public base URL of this ACME server, e.g. `https://acme.example.com`
    pub base_url: String,
    pub database: DatabaseConfig,
    #[serde(rename = "ca", deserialize_with = "deserialize_ca_array")]
    pub cas: Vec<CaConfig>,
    /// Global MTC configuration (deprecated — use per-CA `[ca.mtc]` instead).
    /// When present and a CA has no `[ca.mtc]`, the global section is used as
    /// a fallback for backward compatibility.
    #[serde(default)]
    pub mtc: Option<MtcConfig>,
    #[serde(default)]
    pub server: ServerConfig,
    /// Server-side TLS. Absent or `enabled = false` → plain HTTP, no behavior change.
    #[serde(default)]
    pub tls: TlsConfig,
    /// Certificate profile providers.  When absent, orders without a `profile`
    /// field fall back to CA defaults; the deprecated `server.profiles` map
    /// still governs directory advertisement in that case.
    #[serde(default)]
    pub profiles: ProfilesConfig,
    /// Admin API configuration.  Absent → admin endpoints return 404.
    #[serde(default)]
    pub admin: Option<AdminConfig>,
    /// RFC 8823 S/MIME email-reply-00 challenge support.
    /// Absent or `enabled = false` → "email" identifier type is rejected.
    #[serde(default)]
    pub email_challenge: Option<EmailChallengeConfig>,
    /// Upstream CA configuration for the IdO→CA leg of RFC 9115.
    /// When absent, delegation orders are issued directly by Akamu's own CA.
    #[serde(default)]
    pub delegation_upstream: Option<DelegationUpstreamConfig>,
    /// RFC 9447 tkauth-01 / RFC 9448 TNAuthList / jwtclaimcon authority token challenge support.
    /// Absent or `enabled = false` → "TNAuthList" and "EnhancedJWTClaimConstraints" identifiers rejected.
    #[serde(default)]
    pub tkauth: Option<TkauthConfig>,
    /// CRDT gossip replication. Absent → single-node mode; no gossip is performed.
    #[serde(default)]
    pub gossip: Option<GossipConfig>,
    /// URL for the dedicated CRDT database pool.  When absent, derived from
    /// `database.url` by appending `_crdt` before the `.db` extension (SQLite)
    /// or reusing the same URL with a separate pool (non-SQLite).
    #[serde(default)]
    pub crdt_db_url: Option<String>,
}

/// RFC 8823 S/MIME email-reply-00 challenge configuration.
///
/// When present and `enabled = true`, the server accepts `"email"` identifiers in
/// new-order requests and offers the `"email-reply-00"` challenge.
///
/// ```toml
/// [email_challenge]
/// enabled             = true
/// from_address        = "acme-validation@example.com"
/// send_script         = "/etc/akamu/send-email.sh"
/// # Generate with: openssl rand -hex 32
/// webhook_hmac_secret = "<replace-with-strong-secret>"
/// ```
///
/// The `send_script` is invoked for each challenge with these environment variables:
///
/// | Variable              | Value                                          |
/// |-----------------------|------------------------------------------------|
/// | `ACME_TO`             | Recipient email address (the identifier value) |
/// | `ACME_FROM`           | Server's From: address (`from_address`)        |
/// | `ACME_SUBJECT`        | `ACME: <base64url(token-part1)>` per RFC 8823  |
/// | `ACME_MESSAGE_ID`     | `<uuid@from-domain>` generated by the server   |
/// | `ACME_AUTO_SUBMITTED` | `auto-generated; type=acme`                    |
///
/// Exit code 0 = success; non-zero = challenge fails (client may retry).
///
/// Inbound client reply emails are received via the webhook endpoint at
/// `POST /acme/email-webhook`.  Callers authenticate with the header
/// `X-Akamu-Signature: sha256=<hex(HMAC-SHA256(body, webhook_hmac_secret))>`.
/// The secret must be at least 32 characters (256 bits) of random data.
#[derive(Deserialize, Clone)]
pub struct EmailChallengeConfig {
    /// Offer the email-reply-00 challenge type. Default: false.
    #[serde(default)]
    pub enabled: bool,
    /// `From:` address placed in challenge emails sent by `send_script`.
    #[serde(default)]
    pub from_address: String,
    /// Absolute path to the executable that sends the challenge email.
    #[serde(default)]
    pub send_script: String,
    /// Timeout in seconds for `send_script` execution (default 30).
    #[serde(default = "default_send_script_timeout_secs")]
    pub send_script_timeout_secs: u64,
    /// Shared secret (≥ 32 chars) for `POST /acme/email-webhook` HMAC authentication.
    #[serde(default)]
    pub webhook_hmac_secret: String,
}

fn default_send_script_timeout_secs() -> u64 {
    30
}

impl std::fmt::Debug for EmailChallengeConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EmailChallengeConfig")
            .field("enabled", &self.enabled)
            .field("from_address", &self.from_address)
            .field("send_script", &self.send_script)
            .field("webhook_hmac_secret", &"[REDACTED]")
            .finish()
    }
}

/// One entry in `[[tkauth.claim_encoders]]`.
///
/// Maps a JWT claim name in the authority token payload to a built-in
/// certificate extension encoder.
///
/// ```toml
/// [[tkauth.claim_encoders]]
/// claim         = "krb5-principal"
/// encoder       = "krb5-kpn"
/// default_realm = "EXAMPLE.COM"   # optional — appended when value has no '@'
///
/// [[tkauth.claim_encoders]]
/// claim   = "ms-upn"
/// encoder = "ms-upn"
/// ```
///
/// Supported encoder names: `"krb5-kpn"`, `"ms-upn"`.
#[derive(Debug, Deserialize, Clone)]
pub struct ClaimEncoderEntry {
    /// JWT claim name in the authority token payload.
    pub claim: String,
    /// Built-in encoder name: `"krb5-kpn"`, `"ms-upn"`, or `"dns-san"`.
    pub encoder: String,
    /// Default Kerberos realm appended when the claim value contains no `@`.
    /// Only meaningful for `"krb5-kpn"`.
    pub default_realm: Option<String>,
}

/// RFC 9447 tkauth-01 authority token challenge configuration.
///
/// When present and `enabled = true`, the server accepts `"TNAuthList"` (RFC 9448) and
/// `"EnhancedJWTClaimConstraints"` (draft-ietf-acme-authority-token-jwtclaimcon) identifier types
/// and offers the `"tkauth-01"` challenge type.
///
/// ```toml
/// [tkauth]
/// enabled                 = true
/// trusted_ta_ca_files     = ["/etc/akamu/tn-authority-root.pem"]
/// token_authority_url     = "https://ta.example.com"
/// max_validity_secs       = 3600
/// jti_prune_interval_secs = 3600
///
/// [[tkauth.claim_encoders]]
/// claim         = "krb5-principal"
/// encoder       = "krb5-kpn"
/// default_realm = "EXAMPLE.COM"
/// ```
#[derive(Debug, Deserialize, Clone)]
pub struct TkauthConfig {
    /// Enable tkauth-01 challenge type. Default: false.
    #[serde(default)]
    pub enabled: bool,
    /// PEM files for trusted Token Authority CA certificates.
    /// The signing certificate from the authority token's x5u/x5c must chain
    /// to one of these roots.  Required (non-empty) when `enabled = true`.
    #[serde(default)]
    pub trusted_ta_ca_files: Vec<String>,
    /// Optional `token-authority` URL hint included in tkauth-01 challenge responses.
    pub token_authority_url: Option<String>,
    /// Cap on token lifetime: tokens with `exp − now > max_validity_secs` are rejected.
    /// Default: 3600 (1 hour).
    #[serde(default = "default_tkauth_max_validity_secs")]
    pub max_validity_secs: u64,
    /// Seconds between automatic JTI cache pruning background task runs.
    /// Default: 3600 (1 hour).
    #[serde(default = "default_tkauth_jti_prune_interval_secs")]
    pub jti_prune_interval_secs: u64,
    /// Claim-to-extension encoder entries for `JWTClaimConstraints` finalize injection.
    /// Each validated `must-include` claim whose name appears here will produce one
    /// OtherName SAN per value in the issued certificate.
    /// Empty (the default) means no claim-derived extension injection.
    #[serde(default)]
    pub claim_encoders: Vec<ClaimEncoderEntry>,
}

fn default_tkauth_max_validity_secs() -> u64 {
    3600
}

fn default_tkauth_jti_prune_interval_secs() -> u64 {
    3600
}

/// CRDT gossip replication configuration.
///
/// When this section is present, Akamu gossips CRDT deltas to the listed peers.
/// When absent, the node runs in single-node mode (no replication).
///
/// ```toml
/// [gossip]
/// peers = ["https://node2.acme.internal:8081"]
/// interval_secs = 15
/// tombstone_ttl_secs = 604800
/// ownership_ttl_secs = 150
/// ```
#[derive(Debug, Deserialize, Clone)]
pub struct GossipConfig {
    /// Peer gossip URLs to push CRDT state to.
    #[serde(default)]
    pub peers: Vec<String>,
    /// Gossip round interval in seconds. Default: 15.
    #[serde(default = "default_gossip_interval_secs")]
    pub interval_secs: u64,
    /// Tombstone TTL in seconds. Default: 604800 (7 days).
    #[serde(default = "default_gossip_tombstone_ttl_secs")]
    pub tombstone_ttl_secs: u64,
    /// Order/MTC writer ownership TTL in seconds. Default: 150.
    #[serde(default = "default_gossip_ownership_ttl_secs")]
    pub ownership_ttl_secs: u64,
    /// Maximum age of a gossip envelope in seconds before it is rejected as a
    /// potential replay. Default: 300 (5 minutes).
    #[serde(default = "default_gossip_envelope_max_age_secs")]
    pub gossip_envelope_max_age_secs: u64,
    /// Acceptable clock skew between nodes in seconds; envelopes issued more
    /// than this many seconds in the future are rejected. Default: 30.
    #[serde(default = "default_gossip_clock_skew_tolerance_secs")]
    pub clock_skew_tolerance_secs: u64,
    /// Maximum peers to contact per gossip round (fan-out limit).
    /// Zero (the default) means all known peers.  Setting this to 3–5
    /// reduces O(N²) gossip overhead in clusters larger than ~5 nodes
    /// while convergence still happens transitively in O(log_k(N)) rounds.
    #[serde(default)]
    pub fan_out: usize,
}

fn default_gossip_interval_secs() -> u64 {
    15
}

fn default_gossip_tombstone_ttl_secs() -> u64 {
    604_800 // 7 days
}

fn default_gossip_ownership_ttl_secs() -> u64 {
    150
}

fn default_gossip_envelope_max_age_secs() -> u64 {
    300
}

fn default_gossip_clock_skew_tolerance_secs() -> u64 {
    30
}

impl Default for GossipConfig {
    fn default() -> Self {
        Self {
            peers: Vec::new(),
            interval_secs: default_gossip_interval_secs(),
            tombstone_ttl_secs: default_gossip_tombstone_ttl_secs(),
            ownership_ttl_secs: default_gossip_ownership_ttl_secs(),
            gossip_envelope_max_age_secs: default_gossip_envelope_max_age_secs(),
            clock_skew_tolerance_secs: default_gossip_clock_skew_tolerance_secs(),
            fan_out: 0,
        }
    }
}

fn is_valid_ca_id(id: &str) -> bool {
    // max 64 chars: matches MariaDB VARCHAR(64) column for ca_id
    // lowercase-only so reserved-segment checks are unambiguous and Axum
    // route matching stays consistent (paths are case-sensitive).
    if id.is_empty() || id.len() > 64 {
        return false;
    }
    let mut chars = id.chars();
    match chars.next() {
        None => return false,
        Some(c) => {
            if !c.is_ascii_lowercase() && !c.is_ascii_digit() {
                return false;
            }
        }
    }
    chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-')
}

/// Deserialize either a `[ca]` single-table (backward compat) or a
/// `[[ca]]` array-of-tables into `Vec<CaConfig>`.
///
/// When the TOML source uses the old `[ca]` form the resulting single entry
/// gets `id = "default"` and `is_default = true` injected automatically so
/// the rest of the codebase can treat multi-CA and single-CA configs uniformly.
fn deserialize_ca_array<'de, D>(deserializer: D) -> Result<Vec<CaConfig>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::de::{MapAccess, SeqAccess, Visitor};
    use std::fmt;

    struct CaArrayVisitor;

    impl<'de> Visitor<'de> for CaArrayVisitor {
        type Value = Vec<CaConfig>;

        fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.write_str("a [ca] table or [[ca]] array of tables")
        }

        fn visit_seq<A: SeqAccess<'de>>(self, mut seq: A) -> Result<Vec<CaConfig>, A::Error> {
            let mut cas = Vec::new();
            while let Some(ca) = seq.next_element::<CaConfig>()? {
                cas.push(ca);
            }
            Ok(cas)
        }

        fn visit_map<M: MapAccess<'de>>(self, map: M) -> Result<Vec<CaConfig>, M::Error> {
            let mut ca = CaConfig::deserialize(serde::de::value::MapAccessDeserializer::new(map))?;
            if ca.id.is_empty() {
                ca.id = "default".to_owned();
            }
            ca.is_default = true;
            Ok(vec![ca])
        }
    }

    deserializer.deserialize_any(CaArrayVisitor)
}

/// ACME path segments that are not valid CA identifiers.
///
/// CA IDs must not collide with these because both the legacy `/acme/{segment}`
/// and the per-CA `/acme/{ca_id}/{segment}` routes share the same URL tree.
/// This list is used in [`Config::validate`] and exported so the router can
/// enforce the same constraint without duplicating it.
pub const RESERVED_CA_IDS: &[&str] = &[
    // NOTE: "default" is intentionally excluded from this list because the legacy
    // single-[ca] compatibility mode auto-assigns id = "default" to the sole CA.
    // The constraint for "default" is enforced separately below: it may only be
    // used as the CA ID when is_default = true (so migration sentinel rows point
    // to the correct CA).
    "directory",
    "new-nonce",
    "new-account",
    "new-order",
    "new-authz",
    "revoke-cert",
    "key-change",
    "renewal-info",
    "cert",
    "order",
    "authz",
    "chall",
    "eab",
    "mtc",
    "account",
];

impl Config {
    pub fn from_file(path: &str) -> Result<Self, String> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("cannot read config file '{}': {}", path, e))?;
        let config: Self =
            toml::from_str(&content).map_err(|e| format!("config parse error: {}", e))?;
        config.validate()?;
        Ok(config)
    }

    /// Validate semantic constraints on the config that cannot be expressed with
    /// serde alone.  Called automatically by [`Self::from_file`].  Unit tests that
    /// construct configs via `toml::from_str` directly may call this manually.
    pub fn validate(&self) -> Result<(), String> {
        if self.cas.is_empty() {
            return Err("at least one [ca] or [[ca]] entry is required".into());
        }

        for ca in &self.cas {
            if ca.id.is_empty() {
                return Err("each [[ca]] entry must have a non-empty `id` field".into());
            }
            if !is_valid_ca_id(&ca.id) {
                return Err(format!(
                    "CA id {:?} must match ^[a-z0-9][a-z0-9_-]*$",
                    ca.id
                ));
            }
            if RESERVED_CA_IDS.contains(&ca.id.as_str()) {
                return Err(format!(
                    "CA id {:?} is a reserved ACME path segment and cannot be used",
                    ca.id
                ));
            }
            // "default" is the migration backfill sentinel; only the default CA may use it.
            // The legacy [ca] format auto-injects id="default" with is_default=true, which is correct.
            if ca.id == "default" && !ca.is_default {
                return Err(
                    "CA id \"default\" is the migration sentinel and may only be used on the \
                     default CA (is_default = true)"
                        .into(),
                );
            }
        }

        let mut seen = std::collections::HashSet::new();
        for ca in &self.cas {
            if !seen.insert(ca.id.as_str()) {
                return Err(format!("duplicate CA id {:?}", ca.id));
            }
        }

        if self.cas.len() > 1 {
            let default_count = self.cas.iter().filter(|c| c.is_default).count();
            if default_count == 0 {
                return Err(
                    "with multiple [[ca]] entries, exactly one must have `is_default = true`"
                        .into(),
                );
            }
            if default_count > 1 {
                return Err("at most one [[ca]] entry may have `is_default = true`".into());
            }
        }

        match self.server.account_scope.as_str() {
            "server" | "ca" => {}
            other => {
                return Err(format!(
                    "[server].account_scope must be \"server\" or \"ca\", got {:?}",
                    other
                ));
            }
        }

        // Validate that ca_ids in builtin profiles reference configured CAs.
        let known_ca_ids: std::collections::HashSet<&str> =
            self.cas.iter().map(|c| c.id.as_str()).collect();
        for (provider_name, provider) in &self.profiles.providers {
            if let ProviderConfig::Builtin(builtin) = provider {
                for (profile_name, profile) in &builtin.profiles {
                    for ca_id in &profile.ca_ids {
                        if !known_ca_ids.contains(ca_id.as_str()) {
                            return Err(format!(
                                "profile {profile_name:?} in provider {provider_name:?}: \
                                 ca_ids references unknown CA id {ca_id:?}"
                            ));
                        }
                    }
                }
            }
        }

        if let Some(du) = &self.delegation_upstream {
            const VALID_SOLVERS: &[&str] = &["dns-01", "http-01", "tls-alpn-01"];
            if du.directory_url.is_empty() {
                return Err("[delegation_upstream].directory_url must not be empty".into());
            }
            if !du.directory_url.starts_with("https://") {
                return Err(format!(
                    "[delegation_upstream].directory_url {:?} must use https://",
                    du.directory_url
                ));
            }
            if du.account_key_file.is_empty() {
                return Err("[delegation_upstream].account_key_file must not be empty".into());
            }
            if !std::path::Path::new(&du.account_key_file).is_absolute() {
                return Err(format!(
                    "[delegation_upstream].account_key_file {:?} must be an absolute path",
                    du.account_key_file
                ));
            }
            if !VALID_SOLVERS.contains(&du.challenge_solver.as_str()) {
                return Err(format!(
                    "[delegation_upstream].challenge_solver {:?} must be one of: {}",
                    du.challenge_solver,
                    VALID_SOLVERS.join(", ")
                ));
            }
            if du.poll_interval_secs == 0 {
                return Err("[delegation_upstream].poll_interval_secs must be at least 1".into());
            }
            if du.challenge_solver == "dns-01" && du.challenge_deploy_script.is_none() {
                return Err("[delegation_upstream].challenge_deploy_script is required \
                     when challenge_solver = \"dns-01\""
                    .into());
            }
            if let Some(ref script) = du.challenge_deploy_script {
                if !std::path::Path::new(script).is_absolute() {
                    return Err(format!(
                        "[delegation_upstream].challenge_deploy_script {script:?} must be an absolute path"
                    ));
                }
            }
            if let Some(ref script) = du.challenge_cleanup_script {
                if !std::path::Path::new(script).is_absolute() {
                    return Err(format!(
                        "[delegation_upstream].challenge_cleanup_script {script:?} must be an absolute path"
                    ));
                }
            }
        }

        if let Some(wu) = &self.server.webui {
            if let Some(ref dir) = wu.static_dir {
                if !std::path::Path::new(dir).is_absolute() {
                    return Err(format!(
                        "[server.webui].static_dir {dir:?} must be an absolute path"
                    ));
                }
            }
        }

        if let Some(ec) = &self.email_challenge {
            // Format/security checks run unconditionally whenever the section is present,
            // so a misconfigured disabled section is still caught at startup.
            if !ec.from_address.is_empty()
                && ec
                    .from_address
                    .split_once('@')
                    .is_none_or(|(l, d)| l.is_empty() || !d.contains('.'))
            {
                return Err(format!(
                    "[email_challenge].from_address {:?} is not a valid email address \
                     (expected local-part@domain.tld)",
                    ec.from_address
                ));
            }
            if !ec.send_script.is_empty() && !std::path::Path::new(&ec.send_script).is_absolute() {
                return Err(format!(
                    "[email_challenge].send_script {:?} must be an absolute path",
                    ec.send_script
                ));
            }
            if !ec.webhook_hmac_secret.is_empty() && ec.webhook_hmac_secret.len() < 32 {
                return Err(
                    "[email_challenge].webhook_hmac_secret must be at least 32 characters \
                     (generate with: openssl rand -hex 32)"
                        .into(),
                );
            }
            if ec.enabled {
                if ec.from_address.is_empty() {
                    return Err(
                        "[email_challenge].from_address must not be empty when enabled".into(),
                    );
                }
                if ec.send_script.is_empty() {
                    return Err(
                        "[email_challenge].send_script must not be empty when enabled".into(),
                    );
                }
                if ec.webhook_hmac_secret.is_empty() {
                    return Err(
                        "[email_challenge].webhook_hmac_secret must not be empty when enabled"
                            .into(),
                    );
                }
                if ec.send_script_timeout_secs == 0 {
                    return Err(
                        "[email_challenge].send_script_timeout_secs must be at least 1".into(),
                    );
                }
            }
        }

        if let Some(ref mtc_cfg) = self.mtc {
            if let Err(e) = mtc_cfg.hash_alg.parse::<synta_mtc::crypto::HashAlgorithm>() {
                return Err(format!("[mtc].hash_alg: {e}"));
            }
        }
        for ca_cfg in &self.cas {
            if let Some(ref mtc_cfg) = ca_cfg.mtc {
                if let Err(e) = mtc_cfg.hash_alg.parse::<synta_mtc::crypto::HashAlgorithm>() {
                    return Err(format!("[ca.mtc].hash_alg for CA '{}': {e}", ca_cfg.id));
                }
            }
        }

        let is_unix = self.listen_addr.starts_with("unix:") || self.listen_addr.starts_with('/');
        if self.tls.enabled && is_unix {
            return Err("TLS cannot be used with a Unix domain socket listener".to_owned());
        }

        if let Some(tkauth) = &self.tkauth {
            if tkauth.max_validity_secs == 0 {
                return Err("[tkauth].max_validity_secs must be at least 1".into());
            }
            if tkauth.jti_prune_interval_secs == 0 {
                return Err("[tkauth].jti_prune_interval_secs must be at least 1".into());
            }
            if tkauth.enabled {
                if tkauth.trusted_ta_ca_files.is_empty() {
                    return Err(
                        "[tkauth].trusted_ta_ca_files must not be empty when enabled".into(),
                    );
                }
                for path in &tkauth.trusted_ta_ca_files {
                    if !std::path::Path::new(path).is_absolute() {
                        return Err(format!(
                            "[tkauth].trusted_ta_ca_files: '{path}' must be an absolute path"
                        ));
                    }
                }
            }
        }

        if let Some(ref gcfg) = self.server.gssapi {
            if !gcfg.gssproxy && gcfg.keytab_file.is_none() {
                return Err(
                    "[server.gssapi]: set `keytab_file` or enable `gssproxy = true`".into(),
                );
            }
            if gcfg.gssproxy && gcfg.keytab_file.is_some() {
                return Err(
                    "[server.gssapi]: `keytab_file` and `gssproxy = true` are mutually exclusive"
                        .into(),
                );
            }
        }

        if let Some(ref admin) = self.admin {
            if let Some(ref gcfg) = admin.gssapi {
                if !gcfg.gssproxy && gcfg.keytab_file.is_none() {
                    return Err(
                        "[admin.gssapi]: set `keytab_file` or enable `gssproxy = true`".into(),
                    );
                }
                if gcfg.gssproxy && gcfg.keytab_file.is_some() {
                    return Err(
                        "[admin.gssapi]: `keytab_file` and `gssproxy = true` are mutually exclusive"
                            .into(),
                    );
                }
            }
        }

        Ok(())
    }

    /// Returns the default CA config: the one with `is_default = true`, or the
    /// only CA when there is exactly one `[[ca]]` entry.
    ///
    /// # Panics
    ///
    /// Panics if `cas` is empty or no CA is marked default in a multi-CA
    /// config.  [`Self::validate`] prevents both situations when loading from a file.
    pub fn default_ca(&self) -> &CaConfig {
        if self.cas.len() == 1 {
            return &self.cas[0];
        }
        self.cas
            .iter()
            .find(|c| c.is_default)
            .expect("validate() ensures exactly one default CA when multiple CAs are configured")
    }

    /// Returns the list of issuer domains used for dns-persist-01 TXT record
    /// validation and the `issuer-domain-names` challenge field.
    ///
    /// Uses `server.dns_persist_issuer_domains` when explicitly configured;
    /// otherwise falls back to the host portion of `base_url`.
    pub fn dns_persist_issuer_domains(&self) -> Vec<String> {
        if !self.server.dns_persist_issuer_domains.is_empty() {
            return self.server.dns_persist_issuer_domains.clone();
        }
        // Extract host from base_url: strip scheme, then take up to first '/' or ':'
        let without_scheme = self
            .base_url
            .strip_prefix("https://")
            .or_else(|| self.base_url.strip_prefix("http://"))
            .unwrap_or(&self.base_url);
        let host = without_scheme.split('/').next().unwrap_or(without_scheme);
        let host = host.split(':').next().unwrap_or(host);
        vec![host.to_string()]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn minimal_toml() -> &'static str {
        r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"

[database]
url = "sqlite:///tmp/test.db"

[ca]
key_file = "/tmp/ca.key"
cert_file = "/tmp/ca.crt"

[mtc]
log_path = "/tmp/mtc.log"
enabled = false
"#
    }

    #[test]
    fn parse_minimal_config() {
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        assert_eq!(cfg.listen_addr, "127.0.0.1:8080");
        assert_eq!(cfg.base_url, "https://acme.example.com");
        assert_eq!(cfg.database.url, "sqlite:///tmp/test.db");
        assert!(cfg.database.max_connections.is_none());
        let ca = cfg.default_ca();
        assert_eq!(ca.key_file, "/tmp/ca.key");
        assert_eq!(ca.cert_file, "/tmp/ca.crt");
        let mtc = cfg.mtc.as_ref().expect("global mtc section");
        assert_eq!(mtc.log_path, "/tmp/mtc.log");
        assert!(!mtc.enabled);
    }

    #[test]
    fn legacy_ca_table_gets_default_id_and_is_default() {
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        assert_eq!(cfg.cas.len(), 1);
        assert_eq!(cfg.cas[0].id, "default");
        assert!(cfg.cas[0].is_default);
    }

    #[test]
    fn config_ca_defaults_applied() {
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        let ca = cfg.default_ca();
        assert_eq!(ca.key_type, "ec:P-256");
        assert_eq!(ca.hash_alg, "sha256");
        assert_eq!(ca.validity_days, 90);
        assert_eq!(ca.common_name, "ACME Server CA");
        assert_eq!(ca.organization, "ACME Server");
        assert_eq!(ca.ca_validity_years, 10);
        assert!(ca.crl_url.is_none());
        assert!(ca.ocsp_url.is_none());
    }

    #[test]
    fn config_server_defaults_applied_when_section_present() {
        // When [server] section is present, serde uses the `default = "fn"` defaults
        let toml_with_empty_server = format!("{}\n[server]\n", minimal_toml());
        let cfg: Config = toml::from_str(&toml_with_empty_server).unwrap();
        assert_eq!(cfg.server.order_expiry_secs, 86400);
        assert_eq!(cfg.server.authz_expiry_secs, 86400);
        assert_eq!(cfg.server.max_body_bytes, 65536);
        assert!(!cfg.server.external_account_required);
        assert!(cfg.server.caa_identities.is_empty());
        assert!(cfg.server.terms_of_service_url.is_none());
        assert!(cfg.server.website_url.is_none());
        assert!(cfg.server.dns_persist_issuer_domains.is_empty());
        assert_eq!(cfg.server.ari_retry_after_secs, 21600);
    }

    #[test]
    fn dns_persist_issuer_domains_uses_explicit_string() {
        let toml = format!(
            "{}\n[server]\ndns_persist_issuer_domains = \"ca.example.org\"\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert_eq!(cfg.dns_persist_issuer_domains(), vec!["ca.example.org"]);
    }

    #[test]
    fn dns_persist_issuer_domains_accepts_array() {
        let toml = format!(
            "{}\n[server]\ndns_persist_issuer_domains = [\"ca.example.org\", \"ca2.example.org\"]\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert_eq!(
            cfg.dns_persist_issuer_domains(),
            vec!["ca.example.org", "ca2.example.org"]
        );
    }

    #[test]
    fn dns_persist_issuer_domains_falls_back_to_base_url_https() {
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        // base_url = "https://acme.example.com" → host = "acme.example.com"
        assert_eq!(cfg.dns_persist_issuer_domains(), vec!["acme.example.com"]);
    }

    #[test]
    fn dns_persist_issuer_domains_strips_port_from_base_url() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com:8443"
[database]
url = "sqlite::memory:"
[ca]
key_file = "/tmp/ca.key"
cert_file = "/tmp/ca.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        assert_eq!(cfg.dns_persist_issuer_domains(), vec!["acme.example.com"]);
    }

    #[test]
    fn config_optional_fields() {
        let toml = r#"
listen_addr = "0.0.0.0:443"
base_url = "https://ca.example.org"

[database]
url = "sqlite::memory:"

[ca]
key_file = "/etc/ca.key"
cert_file = "/etc/ca.crt"
key_type = "rsa:4096"
hash_alg = "sha512"
validity_days = 365
crl_url = "http://crl.example.org/ca.crl"
ocsp_url = "http://ocsp.example.org"
common_name = "Test CA"
organization = "Test Org"
ca_validity_years = 5

[mtc]
log_path = "/var/mtc.log"
enabled = true

[server]
terms_of_service_url = "https://example.org/tos"
website_url = "https://example.org"
caa_identities = ["ca.example.org"]
external_account_required = true
order_expiry_secs = 3600
authz_expiry_secs = 7200
max_body_bytes = 131072
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let ca = cfg.default_ca();
        assert_eq!(ca.key_type, "rsa:4096");
        assert_eq!(ca.hash_alg, "sha512");
        assert_eq!(ca.validity_days, 365);
        assert_eq!(ca.crl_url.as_deref(), Some("http://crl.example.org/ca.crl"));
        assert_eq!(ca.ocsp_url.as_deref(), Some("http://ocsp.example.org"));
        assert_eq!(ca.ca_validity_years, 5);
        assert!(cfg.mtc.as_ref().unwrap().enabled);
        assert_eq!(
            cfg.server.terms_of_service_url.as_deref(),
            Some("https://example.org/tos")
        );
        assert_eq!(
            cfg.server.website_url.as_deref(),
            Some("https://example.org")
        );
        assert_eq!(cfg.server.caa_identities, vec!["ca.example.org"]);
        assert!(cfg.server.external_account_required);
        assert_eq!(cfg.server.order_expiry_secs, 3600);
        assert_eq!(cfg.server.authz_expiry_secs, 7200);
        assert_eq!(cfg.server.max_body_bytes, 131072);
    }

    #[test]
    fn ari_retry_after_secs_explicit_and_default() {
        let toml_explicit = format!(
            "{}\n[server]\nari_retry_after_secs = 3600\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml_explicit).unwrap();
        assert_eq!(cfg.server.ari_retry_after_secs, 3600);

        // Default when [server] section is present but field is absent.
        // (When the section is completely absent, Rust's Default impl is used instead.)
        let toml_section_only = format!("{}\n[server]\n", minimal_toml());
        let cfg_default: Config = toml::from_str(&toml_section_only).unwrap();
        assert_eq!(cfg_default.server.ari_retry_after_secs, 21600);
    }

    #[test]
    fn from_file_missing_returns_error() {
        let result = Config::from_file("/nonexistent/path/config.toml");
        assert!(result.is_err());
        let msg = result.unwrap_err();
        assert!(msg.contains("cannot read config file"), "msg: {msg}");
    }

    #[test]
    fn from_file_invalid_toml_returns_error() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(f, "this is not valid toml = = =").unwrap();
        let result = Config::from_file(f.path().to_str().unwrap());
        assert!(result.is_err());
        let msg = result.unwrap_err();
        assert!(msg.contains("config parse error"), "msg: {msg}");
    }

    #[test]
    fn from_file_valid_config() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(f, "{}", minimal_toml()).unwrap();
        let cfg = Config::from_file(f.path().to_str().unwrap()).unwrap();
        assert_eq!(cfg.listen_addr, "127.0.0.1:8080");
    }

    #[test]
    fn trusted_proxies_absent_defaults_to_empty() {
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        assert!(cfg.server.trusted_proxies.is_empty());
    }

    #[test]
    fn trusted_proxies_parses_cidr_list() {
        let toml = format!(
            "{}\n[server]\ntrusted_proxies = [\"127.0.0.1/32\", \"::1/128\", \"10.0.0.0/8\"]\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert_eq!(cfg.server.trusted_proxies.len(), 3);
        let strs: Vec<String> = cfg
            .server
            .trusted_proxies
            .iter()
            .map(|n| n.to_string())
            .collect();
        assert!(strs.contains(&"127.0.0.1/32".to_owned()));
        assert!(strs.contains(&"::1/128".to_owned()));
        assert!(strs.contains(&"10.0.0.0/8".to_owned()));
    }

    #[test]
    fn trusted_proxies_invalid_cidr_returns_error() {
        let toml = format!(
            "{}\n[server]\ntrusted_proxies = [\"not-a-cidr\"]\n",
            minimal_toml()
        );
        assert!(toml::from_str::<Config>(&toml).is_err());
    }

    #[test]
    fn gssapi_absent_is_none() {
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        assert!(cfg.server.gssapi.is_none());
    }

    #[test]
    fn gssapi_section_parses_explicit_values() {
        let toml = format!(
            "{}\n[server.gssapi]\nkeytab_file = \"/etc/akamu/http.keytab\"\nservice_name = \"HTTP@host.example.com\"\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        let gcfg = cfg.server.gssapi.expect("gssapi should be Some");
        assert_eq!(gcfg.keytab_file.as_deref(), Some("/etc/akamu/http.keytab"));
        assert_eq!(gcfg.service_name, "HTTP@host.example.com");
    }

    #[test]
    fn eab_master_secret_absent_is_none() {
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        assert!(cfg.server.eab_master_secret.is_none());
    }

    #[test]
    fn eab_master_secret_present_parses() {
        let toml = format!(
            "{}\n[server]\neab_master_secret = \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert!(cfg.server.eab_master_secret.is_some());
    }

    #[test]
    fn gssapi_service_name_defaults_to_http() {
        let toml = format!(
            "{}\n[server.gssapi]\nkeytab_file = \"/etc/akamu/http.keytab\"\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        let gcfg = cfg.server.gssapi.expect("gssapi should be Some");
        assert_eq!(gcfg.service_name, "HTTP");
    }

    // ── AdminConfig tests ──────────────────────────────────────────────────────

    fn admin_toml_base() -> String {
        format!(
            r#"{}
[admin]
"#,
            minimal_toml()
        )
    }

    #[test]
    fn admin_config_defaults_parse() {
        let cfg: Config = toml::from_str(&admin_toml_base()).unwrap();
        let admin = cfg.admin.expect("admin should be Some");
        assert!(admin.gssapi.is_none());
        assert_eq!(admin.session_ttl_secs, 3600);
        assert_eq!(admin.audit_overflow, "drop_oldest");
        assert_eq!(admin.audit_alarm_threshold, 10);
        assert_eq!(admin.audit_alarm_action, "syslog");
        assert!(admin.audit_max_rows.is_none());
    }

    #[test]
    fn admin_config_validate_ok_with_gssapi() {
        let toml = format!(
            r#"{}
[admin]

[admin.gssapi]
keytab_file  = "/etc/akamu/http.keytab"
service_name = "HTTP"
"#,
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert!(cfg.admin.unwrap().validate().is_ok());
    }

    #[test]
    fn admin_config_validate_ok_minimal() {
        let cfg: Config = toml::from_str(&admin_toml_base()).unwrap();
        assert!(cfg.admin.unwrap().validate().is_ok());
    }

    #[test]
    fn admin_config_validate_bad_overflow() {
        let toml = format!(
            r#"{}
[admin]
audit_overflow = "delete"
"#,
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        let err = cfg.admin.unwrap().validate().unwrap_err();
        assert!(err.contains("audit_overflow"), "msg: {err}");
    }

    #[test]
    fn admin_config_audit_policy_drop_oldest() {
        let cfg: Config = toml::from_str(&admin_toml_base()).unwrap();
        let policy = crate::audit::AuditPolicy::from_admin_config(&cfg.admin.unwrap());
        assert!(policy.max_events.is_none());
        assert_eq!(policy.overflow, crate::audit::OverflowPolicy::DropOldest);
        assert_eq!(policy.alarm_threshold, 10);
        assert_eq!(policy.alarm_action, crate::audit::AlarmAction::Syslog);
    }

    #[test]
    fn admin_config_audit_policy_halt() {
        let toml = format!(
            r#"{}
[admin]
audit_max_rows        = 500000
audit_overflow        = "halt"
audit_alarm_threshold = 5
audit_alarm_action    = "halt"
"#,
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        let policy = crate::audit::AuditPolicy::from_admin_config(&cfg.admin.unwrap());
        assert_eq!(policy.max_events, Some(500_000));
        assert_eq!(policy.overflow, crate::audit::OverflowPolicy::Halt);
        assert_eq!(policy.alarm_threshold, 5);
        assert_eq!(policy.alarm_action, crate::audit::AlarmAction::Halt);
    }

    // ── Multi-CA config tests ──────────────────────────────────────────────────

    #[test]
    fn multi_ca_array_parses() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"

[database]
url = "sqlite::memory:"

[[ca]]
id = "rsa"
is_default = true
key_file = "/etc/akamu/rsa.key"
cert_file = "/etc/akamu/rsa.crt"

[[ca]]
id = "ec"
key_file = "/etc/akamu/ec.key"
cert_file = "/etc/akamu/ec.crt"

[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        // Validate must also pass (tests the full parse→validate pipeline).
        cfg.validate().unwrap();
        assert_eq!(cfg.cas.len(), 2);
        assert_eq!(cfg.cas[0].id, "rsa");
        assert!(cfg.cas[0].is_default);
        assert_eq!(cfg.cas[1].id, "ec");
        assert!(!cfg.cas[1].is_default);
        assert_eq!(cfg.default_ca().id, "rsa");
    }

    #[test]
    fn default_ca_returns_non_first_default() {
        // Verify that default_ca() uses Iterator::find on is_default, not cas[0].
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "ec"
key_file = "/etc/akamu/ec.key"
cert_file = "/etc/akamu/ec.crt"
[[ca]]
id = "rsa"
is_default = true
key_file = "/etc/akamu/rsa.key"
cert_file = "/etc/akamu/rsa.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        cfg.validate().unwrap();
        assert_eq!(cfg.default_ca().id, "rsa");
    }

    #[test]
    fn multi_ca_validate_rejects_reserved_id_case_insensitive() {
        // "Directory" (mixed case) must be rejected — CA IDs are lowercase-only
        // so mixed-case collisions with reserved path segments cannot happen.
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "Directory"
is_default = true
key_file = "/etc/akamu/ca.key"
cert_file = "/etc/akamu/ca.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let err = cfg.validate().unwrap_err();
        // Mixed-case IDs are now rejected at the format check (lowercase-only)
        // before the reserved-segment check is reached.
        assert!(
            err.contains("reserved") || err.contains("must match"),
            "err: {err}"
        );
    }

    #[test]
    fn multi_ca_validate_requires_default() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "rsa"
key_file = "/etc/akamu/rsa.key"
cert_file = "/etc/akamu/rsa.crt"
[[ca]]
id = "ec"
key_file = "/etc/akamu/ec.key"
cert_file = "/etc/akamu/ec.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(err.contains("is_default"), "err: {err}");
    }

    #[test]
    fn multi_ca_validate_rejects_duplicate_id() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "rsa"
is_default = true
key_file = "/etc/akamu/rsa.key"
cert_file = "/etc/akamu/rsa.crt"
[[ca]]
id = "rsa"
key_file = "/etc/akamu/rsa2.key"
cert_file = "/etc/akamu/rsa2.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(err.contains("duplicate"), "err: {err}");
    }

    #[test]
    fn multi_ca_validate_rejects_reserved_id() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "directory"
is_default = true
key_file = "/etc/akamu/ca.key"
cert_file = "/etc/akamu/ca.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(err.contains("reserved"), "err: {err}");
    }

    #[test]
    fn multi_ca_validate_rejects_invalid_id_chars() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "bad id!"
is_default = true
key_file = "/etc/akamu/ca.key"
cert_file = "/etc/akamu/ca.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(err.contains("must match"), "err: {err}");
    }

    #[test]
    fn multi_ca_validate_rejects_two_defaults() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "rsa"
is_default = true
key_file = "/etc/akamu/rsa.key"
cert_file = "/etc/akamu/rsa.crt"
[[ca]]
id = "ec"
is_default = true
key_file = "/etc/akamu/ec.key"
cert_file = "/etc/akamu/ec.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(err.contains("at most one"), "err: {err}");
    }

    #[test]
    fn account_scope_default_is_server() {
        // When [server] is absent entirely, ServerConfig::Default gives "server".
        let cfg: Config = toml::from_str(minimal_toml()).unwrap();
        assert_eq!(cfg.server.account_scope, "server");

        // When [server] is present but account_scope is absent, serde's
        // default_account_scope() function also gives "server".
        let toml_with_server = format!("{}\n[server]\n", minimal_toml());
        let cfg2: Config = toml::from_str(&toml_with_server).unwrap();
        assert_eq!(cfg2.server.account_scope, "server");
    }

    #[test]
    fn account_scope_ca_parses() {
        let toml = format!("{}\n[server]\naccount_scope = \"ca\"\n", minimal_toml());
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert_eq!(cfg.server.account_scope, "ca");
    }

    #[test]
    fn account_scope_invalid_fails_validate() {
        let toml = format!(
            "{}\n[server]\naccount_scope = \"invalid\"\n",
            minimal_toml()
        );
        let cfg: Config = toml::from_str(&toml).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(err.contains("account_scope"), "err: {err}");
    }

    #[test]
    fn builtin_profile_ca_ids_parses() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[ca]
key_file = "/tmp/ca.key"
cert_file = "/tmp/ca.crt"
[mtc]
log_path = "/dev/null"
enabled = false
[profiles.providers.local]
type = "builtin"
[profiles.providers.local.profiles.tlsserver]
description = "TLS server"
ca_ids = ["rsa", "ec"]
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        let builtin = match cfg.profiles.providers.get("local").expect("local provider") {
            ProviderConfig::Builtin(b) => b,
            _ => panic!("expected builtin"),
        };
        let profile = builtin.profiles.get("tlsserver").expect("tlsserver");
        assert_eq!(profile.ca_ids, vec!["rsa", "ec"]);
    }

    #[test]
    fn multi_ca_caa_identities_per_ca() {
        let toml = r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite::memory:"
[[ca]]
id = "rsa"
is_default = true
key_file = "/etc/akamu/rsa.key"
cert_file = "/etc/akamu/rsa.crt"
caa_identities = ["rsa.example.com"]
[[ca]]
id = "ec"
key_file = "/etc/akamu/ec.key"
cert_file = "/etc/akamu/ec.crt"
[mtc]
log_path = "/dev/null"
enabled = false
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        assert_eq!(cfg.cas[0].caa_identities, vec!["rsa.example.com"]);
        assert!(cfg.cas[1].caa_identities.is_empty());
    }

    fn minimal_toml_with_mtc(hash_alg: &str) -> String {
        format!(
            r#"
listen_addr = "127.0.0.1:8080"
base_url = "https://acme.example.com"
[database]
url = "sqlite:///tmp/test.db"
[ca]
key_file = "/tmp/ca.key"
cert_file = "/tmp/ca.crt"
[mtc]
log_path = "/tmp/mtc.log"
enabled = false
hash_alg = "{hash_alg}"
"#
        )
    }

    #[test]
    fn mtc_hash_alg_invalid_fails_validate() {
        let cfg: Config = toml::from_str(&minimal_toml_with_mtc("md5")).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(err.contains("hash_alg"), "err: {err}");
        assert!(err.contains("md5"), "err: {err}");
    }

    #[test]
    fn mtc_hash_alg_valid_passes_validate() {
        for alg in [
            "sha256", "sha384", "sha512", "sha3-256", "sha3-384", "sha3-512",
        ] {
            let cfg: Config = toml::from_str(&minimal_toml_with_mtc(alg)).unwrap();
            cfg.validate()
                .unwrap_or_else(|e| panic!("hash_alg={alg} rejected: {e}"));
        }
    }
}
