//! Generates a ready-to-use `akamu.toml` from the spec and persisted CA paths.
//!
//! The output directory layout (relative to the parent of `artifacts_dir`) is:
//!
//! ```text
//! <stem>/               ← artifacts_dir
//!   akamu.toml
//!   ca-<id>/
//!     ca.key
//!     ca.crt
//! <stem>.sqlite3        ← database (sibling of artifacts_dir)
//! ```
//!
//! The generated config uses absolute paths for all files (database, CA keys,
//! CA certs) so that `akamu serve` can be run from any working directory.

use std::path::Path;

use akamu::config::CaConfig;

use crate::spec::{ProfileSpec, SeedSpec};

/// Write `artifacts_dir/akamu.toml`.
///
/// `db_filename` is the bare filename of the output database (e.g.
/// `"test-data.sqlite3"`); the config references it as `"../test-data.sqlite3"`
/// relative to the artifacts directory.
pub fn write(
    artifacts_dir: &Path,
    db_filename: &str,
    spec: &SeedSpec,
    ca_configs: &[CaConfig],
) -> Result<(), String> {
    let content = render(artifacts_dir, db_filename, spec, ca_configs);
    let config_path = artifacts_dir.join("akamu.toml");
    std::fs::write(&config_path, content)
        .map_err(|e| format!("write {}: {e}", config_path.display()))?;
    tracing::info!("wrote {}", config_path.display());
    Ok(())
}

fn render(
    artifacts_dir: &Path,
    db_filename: &str,
    spec: &SeedSpec,
    ca_configs: &[CaConfig],
) -> String {
    let mut s = String::with_capacity(4096);

    s.push_str("# Generated by akamu-seedgen — do not edit by hand.\n");
    s.push_str("# Run from this directory: akamu akamu.toml\n\n");

    s.push_str("listen_addr = \"0.0.0.0:8080\"\n");
    s.push_str("base_url    = \"http://localhost:8080\"\n\n");

    // Database — absolute path so the server can be started from any directory.
    let db_abs = artifacts_dir
        .parent()
        .map(|p| p.join(db_filename))
        .unwrap_or_else(|| std::path::PathBuf::from(db_filename));
    let db_abs = db_abs.canonicalize().unwrap_or(db_abs);
    s.push_str("[database]\n");
    s.push_str(&format!(
        "url = \"sqlite://{}\"\n\n",
        db_abs.to_string_lossy()
    ));

    // MTC — disabled; required section, must be present.
    s.push_str("[mtc]\n");
    s.push_str("enabled  = false\n");
    s.push_str("log_path = \"/dev/null\"\n\n");

    // Server — dev-friendly challenge validation settings.
    // http_validation_allow_private_ips lets the in-process challenge responder
    // answer on loopback; http_validation_port matches the well-known port used
    // by a local challenge responder or ACME client in test mode.
    s.push_str("[server]\n");
    s.push_str("http_validation_allow_private_ips = true\n");
    s.push_str("http_validation_port = 5002\n\n");

    // Admin session store — required for EAB web UI login.
    s.push_str("[admin]\n\n");

    // Profiles as a builtin provider so new orders can be issued against the DB.
    if !spec.profile.is_empty() {
        s.push_str("[profiles.providers.seedgen]\n");
        s.push_str("type = \"builtin\"\n\n");
        for p in &spec.profile {
            render_profile(&mut s, p);
        }
    }

    // CAs — use the absolute paths written by server::start().
    for cfg in ca_configs {
        render_ca(&mut s, cfg);
    }

    s
}

fn render_profile(s: &mut String, p: &ProfileSpec) {
    // TOML dotted key: [profiles.providers.seedgen.profiles.<id>]
    // Profile IDs may contain hyphens which are valid in TOML bare keys.
    s.push_str(&format!("[profiles.providers.seedgen.profiles.{}]\n", p.id));
    s.push_str(&format!("description = {}\n", toml_str(&p.description)));
    if let Some(days) = p.validity_days {
        s.push_str(&format!("validity_days = {days}\n"));
    }
    if !p.eku.is_empty() {
        s.push_str(&format!("eku = {}\n", toml_str_array(&p.eku)));
    }
    if !p.key_usage.is_empty() {
        s.push_str(&format!("key_usage = {}\n", toml_str_array(&p.key_usage)));
    }
    if !p.allowed_key_types.is_empty() {
        s.push_str(&format!(
            "allowed_key_types = {}\n",
            toml_str_array(&p.allowed_key_types)
        ));
    }
    s.push('\n');
}

fn render_ca(s: &mut String, cfg: &CaConfig) {
    s.push_str("[[ca]]\n");
    s.push_str(&format!("id                = {}\n", toml_str(&cfg.id)));
    s.push_str(&format!("is_default        = {}\n", cfg.is_default));
    s.push_str(&format!(
        "key_type          = {}\n",
        toml_str(&cfg.key_type)
    ));
    s.push_str(&format!(
        "hash_alg          = {}\n",
        toml_str(&cfg.hash_alg)
    ));
    s.push_str(&format!("validity_days     = {}\n", cfg.validity_days));
    s.push_str(&format!("ca_validity_years = {}\n", cfg.ca_validity_years));
    s.push_str(&format!(
        "common_name       = {}\n",
        toml_str(&cfg.common_name)
    ));
    s.push_str(&format!(
        "organization      = {}\n",
        toml_str(&cfg.organization)
    ));

    // Prefer absolute paths so the config works regardless of working directory.
    let key_abs = abs_path(cfg.key_file.as_deref().unwrap());
    let cert_abs = abs_path(&cfg.cert_file);
    s.push_str(&format!("key_file          = {}\n", toml_str(&key_abs)));
    s.push_str(&format!("cert_file         = {}\n", toml_str(&cert_abs)));
    s.push('\n');
}

/// Return `path` as an absolute string. If it is already absolute, return it
/// as-is. If it is relative, treat it as relative to the process CWD and
/// canonicalize it. Paths stored in `CaConfig` are relative to CWD (not to
/// `artifacts_dir`), so joining with `artifacts_dir` would double the prefix.
fn abs_path(path: &str) -> String {
    let p = std::path::Path::new(path);
    if p.is_absolute() {
        path.to_owned()
    } else {
        p.canonicalize()
            .unwrap_or_else(|_| {
                std::env::current_dir()
                    .map(|cwd| cwd.join(p))
                    .unwrap_or_else(|_| p.to_path_buf())
            })
            .to_string_lossy()
            .into_owned()
    }
}

/// Format a string as a TOML basic string literal (double-quoted, escaped).
fn toml_str(v: &str) -> String {
    // Escape backslash, double-quote, and control characters per TOML spec.
    let mut out = String::with_capacity(v.len() + 2);
    out.push('"');
    for c in v.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Format a `&[String]` as a TOML inline array of strings.
fn toml_str_array(items: &[String]) -> String {
    let inner = items
        .iter()
        .map(|v| toml_str(v))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{inner}]")
}
