apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: akamu

commonLabels:
  app.kubernetes.io/part-of: akamu
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - rbac.yaml
  - configmaps.yaml
  - akamu-deployment.yaml
  - akamu-service.yaml
  - cosigner-deployment.yaml
  - cosigner-service.yaml
  - networkpolicy.yaml
