-- Add local_gen column to all CRDT-tracked tables so the node can resume
-- delta gossip after a restart without re-broadcasting unchanged entries.
-- ALGORITHM=INSTANT avoids a full table rebuild on MariaDB 10.3+.
ALTER TABLE accounts         ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE orders           ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE authorizations   ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE challenges       ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE certificates     ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE eab_keys         ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE operators        ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE delegations      ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE mtc_checkpoints  ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE mtc_cosignatures ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
ALTER TABLE audit_events     ADD COLUMN local_gen BIGINT NOT NULL DEFAULT 0, ALGORITHM=INSTANT;
