[book]
title = "Akāmu documentation"
authors = ["Alexander Bokovoy"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
no-section-label = true
git-repository-url = ""
additional-css = ["theme/synta.css"]
default-theme = "light"
preferred-dark-theme = "navy"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.rustdoc]
command = "python3 ../../scripts/mdbook-copy-api.py"

# Enable the following sections when building a PDF
##[output.pandoc]
##number-internal-headings = false # number headings inside of chapters
##list-internal-headings = false # list internal headings in the table of contents
##
##[output.pandoc.profile.pdf]
##output-file = "akamu-book.pdf"
##to = "latex"
##pdf-engine = "xelatex"
##filters = ["mermaid-filter.lua"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

