use std::path::PathBuf;

use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "akamu", about = "Akāmu ACME certificate authority")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Option<Commands>,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Start the ACME server (default when no subcommand given).
    Serve {
        /// Path to configuration file.
        #[arg(short = 'c', long, default_value = "config.toml")]
        config: PathBuf,
    },
    /// Generate a quickstart configuration file.
    Init {
        /// Base URL of the ACME server (e.g. "https://acme.example.com:9443").
        /// Determines listen_addr, base_url, and the TLS server_name.
        #[arg(short = 'u', long, default_value = "https://localhost:8443")]
        base_url: String,
        /// Output path for the generated config file.
        #[arg(short = 'o', long, default_value = "./config.toml")]
        output: PathBuf,
        /// Directory for generated data (DB, CA certs, admin credentials).
        /// Defaults to ~/.local/share/akamu.
        #[arg(long)]
        data_dir: Option<PathBuf>,
        /// Overwrite existing config file.
        #[arg(long)]
        force: bool,
    },
    /// Print version and build information.
    Version,
}

const QUICKSTART_TEMPLATE: &str = r#"# quickstart.toml — Generated by `akamu init`. Copy, run, done.
#
# Everything auto-generates on first run: CA, TLS cert, admin credentials.
#   WebUI:    {base_url}/ui/  (import admin.p12 into your browser)
#   akamuctl: akamuctl --pkcs12 {data_dir}/admin.p12 operator list
#
# Full reference: config.toml.example

listen_addr = "127.0.0.1:{port}"
base_url    = "{base_url}"

[database]
url = "sqlite://{data_dir}/acme.db"

[ca]
key_file  = "{data_dir}/ca.key.pem"
cert_file = "{data_dir}/ca.cert.pem"

[tls]
enabled     = true
cert_file   = "{data_dir}/server.pem"
key_file    = "{data_dir}/server.key"
server_name = "{server_name}"

[tls.client_auth]
required = false

[admin]
bootstrap_operator_pkcs12_file = "{data_dir}/admin.p12"

[server]
# DNSSEC validation requires a DNSSEC-aware resolver.  Set to true for
# production (required by CA/B Forum BR since 2026-03-15).
validate_dnssec = false

[server.webui]
"#;

pub fn run_init(
    base_url_str: &str,
    output: &std::path::Path,
    data_dir: Option<&std::path::Path>,
    force: bool,
) -> Result<(), String> {
    let url = url::Url::parse(base_url_str)
        .map_err(|e| format!("invalid --base-url '{base_url_str}': {e}"))?;

    if url.scheme() != "https" {
        return Err(format!(
            "--base-url scheme must be 'https', got '{}'",
            url.scheme()
        ));
    }

    let host = url
        .host_str()
        .ok_or_else(|| format!("--base-url '{base_url_str}' has no host"))?;

    let port = url.port().unwrap_or(443);

    let data_dir = match data_dir {
        Some(d) => d.to_path_buf(),
        None => {
            let home = std::env::var("HOME")
                .map_err(|_| "HOME environment variable is not set".to_string())?;
            std::path::PathBuf::from(home).join(".local/share/akamu")
        }
    };

    let data_dir_str = data_dir
        .to_str()
        .ok_or_else(|| "data_dir path is not valid UTF-8".to_string())?;

    if output.exists() && !force {
        return Err(format!(
            "config file '{}' already exists; use --force to overwrite",
            output.display()
        ));
    }

    if !data_dir.exists() {
        std::fs::create_dir_all(&data_dir).map_err(|e| {
            format!("cannot create data directory '{}': {e}", data_dir.display())
        })?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&data_dir, std::fs::Permissions::from_mode(0o700))
                .map_err(|e| {
                    format!(
                        "cannot set permissions on '{}': {e}",
                        data_dir.display()
                    )
                })?;
        }
    }

    let config_content = QUICKSTART_TEMPLATE
        .replace("{base_url}", base_url_str)
        .replace("{port}", &port.to_string())
        .replace("{server_name}", host)
        .replace("{data_dir}", data_dir_str);

    if let Some(parent) = output.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent).map_err(|e| {
                format!("cannot create directory '{}': {e}", parent.display())
            })?;
        }
    }

    std::fs::write(output, &config_content)
        .map_err(|e| format!("cannot write '{}': {e}", output.display()))?;

    println!("Config written to {}", output.display());
    println!();
    println!("Next steps:");
    println!("  1. Run:       akamu");
    println!("  2. WebUI:     {base_url_str}/ui/");
    println!(
        "  3. Admin CLI: akamuctl --pkcs12 {data_dir_str}/admin.p12 \\"
    );
    println!(
        "                  --ca-cert {data_dir_str}/ca.cert.pem \\"
    );
    println!("                  --server-url {base_url_str} operator list");
    println!();
    println!("Admin credentials (PKCS#12) are generated on first server start.");
    println!("Import admin.p12 into your browser for WebUI access.");

    Ok(())
}
