use std::path::PathBuf;

use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "akamu", about = "Akāmu ACME certificate authority")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Option<Commands>,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Start the ACME server (default when no subcommand given).
    Serve {
        /// Path to configuration file.
        #[arg(short = 'c', long, default_value = "config.toml")]
        config: PathBuf,
    },
    /// Generate a quickstart configuration file.
    Init {
        /// Base URL of the ACME server (e.g. "<https://acme.example.com:9443>").
        /// Determines listen_addr, base_url, and the TLS server_name.
        #[arg(short = 'u', long, default_value = "https://localhost:8443")]
        base_url: String,
        /// Output path (default: ./config.toml, or /etc/akamu/config.toml with --system).
        #[arg(short = 'o', long)]
        output: Option<PathBuf>,
        /// Data directory (default: ~/.local/share/akamu, or /var/lib/akamu with --system).
        #[arg(long)]
        data_dir: Option<PathBuf>,
        /// Overwrite existing config file.
        #[arg(long)]
        force: bool,
        /// Use FHS paths for system-wide deployment (/etc/akamu, /var/lib/akamu).
        #[arg(long)]
        system: bool,
        /// Path to a custom quickstart template file (overrides the default).
        #[arg(long, value_name = "FILE")]
        template: Option<PathBuf>,
    },
    /// Print version and build information.
    Version,
}

// Keep in sync with contrib/quickstart.toml.in (packager-facing copy).
const QUICKSTART_TEMPLATE: &str = r#"# quickstart.toml — Generated by `akamu init`. Copy, run, done.
#
# Everything auto-generates on first run: CA, TLS cert, admin credentials.
#   WebUI:    {base_url}/ui/  (import admin.p12 into your browser)
#   akamuctl: akamuctl --pkcs12 {data_dir}/admin.p12 operator list
#
# Full reference: config.toml.example

listen_addr = "{listen_addr}:{port}"
base_url    = "{base_url}"

[database]
url = "sqlite://{data_dir}/acme.db"

[ca]
key_file  = "{data_dir}/ca.key.pem"
cert_file = "{data_dir}/ca.cert.pem"

[tls]
enabled     = true
cert_file   = "{data_dir}/server.pem"
key_file    = "{data_dir}/server.key"
server_name = "{server_name}"

[tls.client_auth]
required = false

[admin]
bootstrap_operator_pkcs12_file = "{data_dir}/admin.p12"

[server]
# DNSSEC validation requires a DNSSEC-aware resolver.  Set to true for
# production (required by CA/B Forum BR since 2026-03-15).
validate_dnssec = false

[server.webui]
"#;

const SYSTEM_TEMPLATE_PATH: &str = "/usr/share/akamu/quickstart.toml.in";

pub struct InitOptions<'a> {
    pub base_url: &'a str,
    pub output: Option<&'a std::path::Path>,
    pub data_dir: Option<&'a std::path::Path>,
    pub force: bool,
    pub system: bool,
    pub template: Option<&'a std::path::Path>,
}

pub fn run_init(opts: &InitOptions<'_>) -> Result<(), String> {
    let base_url_str = opts.base_url;
    let force = opts.force;
    let system = opts.system;
    let template = opts.template;

    let url = url::Url::parse(base_url_str)
        .map_err(|e| format!("invalid --base-url '{base_url_str}': {e}"))?;

    if url.scheme() != "https" {
        return Err(format!(
            "--base-url scheme must be 'https', got '{}'",
            url.scheme()
        ));
    }

    let host = url
        .host_str()
        .ok_or_else(|| format!("--base-url '{base_url_str}' has no host"))?;

    let port = url.port().unwrap_or(443);

    let data_dir = match opts.data_dir {
        Some(d) => d.to_path_buf(),
        None if system => std::path::PathBuf::from("/var/lib/akamu"),
        None => {
            let home = std::env::var("HOME").map_err(|_| {
                "HOME environment variable is not set; \
                     use --data-dir or --system for system-wide paths"
                    .to_string()
            })?;
            std::path::PathBuf::from(home).join(".local/share/akamu")
        }
    };

    let output_buf;
    let output: &std::path::Path = match opts.output {
        Some(p) => p,
        None if system => {
            output_buf = std::path::PathBuf::from("/etc/akamu/config.toml");
            &output_buf
        }
        None => {
            output_buf = std::path::PathBuf::from("./config.toml");
            &output_buf
        }
    };

    let listen_addr = if system { "0.0.0.0" } else { "127.0.0.1" };

    let data_dir_str = data_dir
        .to_str()
        .ok_or_else(|| "data_dir path is not valid UTF-8".to_string())?;

    if data_dir_str.contains('"')
        || data_dir_str.contains('\\')
        || data_dir_str.contains('\n')
        || data_dir_str.contains('\r')
    {
        return Err(format!(
            "data_dir '{}' contains characters unsafe for config generation \
             (quotes, backslashes, or newlines)",
            data_dir.display()
        ));
    }

    if output.exists() && !force {
        return Err(format!(
            "config file '{}' already exists; use --force to overwrite",
            output.display()
        ));
    }

    if !data_dir.exists() {
        std::fs::create_dir_all(&data_dir)
            .map_err(|e| format!("cannot create data directory '{}': {e}", data_dir.display()))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&data_dir, std::fs::Permissions::from_mode(0o700))
                .map_err(|e| format!("cannot set permissions on '{}': {e}", data_dir.display()))?;
        }
    }

    let template_text = if let Some(tpl) = template {
        eprintln!("Using custom template: {}", tpl.display());
        std::fs::read_to_string(tpl)
            .map_err(|e| format!("cannot read template '{}': {e}", tpl.display()))?
    } else {
        match std::fs::read_to_string(SYSTEM_TEMPLATE_PATH) {
            Ok(text) => {
                eprintln!("Using system template: {SYSTEM_TEMPLATE_PATH}");
                text
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => QUICKSTART_TEMPLATE.to_string(),
            Err(e) => {
                return Err(format!(
                    "system template '{SYSTEM_TEMPLATE_PATH}' exists but cannot be read: {e}"
                ));
            }
        }
    };

    let config_content = template_text
        .replace("{base_url}", base_url_str)
        .replace("{port}", &port.to_string())
        .replace("{server_name}", host)
        .replace("{data_dir}", data_dir_str)
        .replace("{listen_addr}", listen_addr);

    if config_content.contains('{') {
        for cap in config_content.match_indices('{') {
            if let Some(end) = config_content[cap.0..].find('}') {
                let placeholder = &config_content[cap.0..cap.0 + end + 1];
                if !placeholder.contains(' ') && !placeholder.contains('\n') {
                    eprintln!("warning: unreplaced placeholder {placeholder} in generated config");
                }
            }
        }
    }

    if let Some(parent) = output.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("cannot create directory '{}': {e}", parent.display()))?;
        }
    }

    std::fs::write(output, &config_content)
        .map_err(|e| format!("cannot write '{}': {e}", output.display()))?;

    println!("Config written to {}", output.display());
    println!();
    println!("Next steps:");
    if system {
        println!("  1. Start:     systemctl enable --now akamu");
    } else {
        println!("  1. Run:       akamu");
    }
    println!("  2. WebUI:     {base_url_str}/ui/");
    println!("  3. Admin CLI: akamuctl --pkcs12 {data_dir_str}/admin.p12 \\");
    println!("                  --ca-cert {data_dir_str}/ca.cert.pem \\");
    println!("                  --server-url {base_url_str} operator list");
    println!();
    println!("Admin credentials (PKCS#12) are generated on first server start.");
    println!("Import admin.p12 into your browser for WebUI access.");
    if system {
        println!();
        println!("Note: listen_addr is 0.0.0.0 (all interfaces). Use a firewall or");
        println!("      reverse proxy to restrict access in production.");
        println!("Logs: journalctl --namespace=akamu -f");
    }

    Ok(())
}
