apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

patches:
  # 2 replicas for staging.
  - target:
      kind: Deployment
      name: akamu
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  # 2 cosigner replicas for staging.
  - target:
      kind: Deployment
      name: cosigner
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
